version: '3.6'

services:
  mirth-database:
    image: mysql:5.6
    command: mysqld --innodb-buffer-pool-size=20M --lower_case_table_names=1
    environment:
      - MYSQL_DATABASE=mirth-test
      - MYSQL_USER=mirth
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports: 
      - 3306:3306
  mirth-connect:
    build: .
    volumes:
      - ./import:/opt/import
    # links:
     # - mirth-database:mysql
    depends_on:
      - mirth-database
  haproxy:
    build: ./haproxy
    ports: 
      - 6661:6661
      - 6662:6662
      - 8080:8080
      - 8443:8443
   # links:
    #  - mirth-connect:mirth
    depends_on:
      - mirth-connect
